package com.mc.dao;

import java.util.List;

import com.mc.pojo.TitleDetails;

public interface TitleDetailsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_title_details
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_title_details
	 * @mbg.generated
	 */
	int insert(TitleDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_title_details
	 * @mbg.generated
	 */
	int insertSelective(TitleDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_title_details
	 * @mbg.generated
	 */
	TitleDetails selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_title_details
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TitleDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_title_details
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TitleDetails record);
	
	List<TitleDetails> selectByAttach(String attach);
}