package com.mc.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mc.pojo.ZhaohangBilling;

public interface ZhaohangBillingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaohang_billing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaohang_billing
     *
     * @mbg.generated
     */
    int insert(ZhaohangBilling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaohang_billing
     *
     * @mbg.generated
     */
    int insertSelective(ZhaohangBilling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaohang_billing
     *
     * @mbg.generated
     */
    ZhaohangBilling selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaohang_billing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZhaohangBilling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaohang_billing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZhaohangBilling record);

	List<String> selectSerialNumber();

	List<ZhaohangBilling> selectAll(String code);
}