package com.mc.pojo;

import java.util.Date;

public class TitleDetails {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.tax_no
	 * @mbg.generated
	 */
	private String taxNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.addr
	 * @mbg.generated
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.bank_type
	 * @mbg.generated
	 */
	private String bankType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.bank_no
	 * @mbg.generated
	 */
	private String bankNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.title_type
	 * @mbg.generated
	 */
	private String titleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.attach
	 * @mbg.generated
	 */
	private String attach;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.from_user_name
	 * @mbg.generated
	 */
	private String fromUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.to_user_name
	 * @mbg.generated
	 */
	private String toUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.msg_type
	 * @mbg.generated
	 */
	private String msgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.event
	 * @mbg.generated
	 */
	private String event;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.code_auth_key
	 * @mbg.generated
	 */
	private String codeAuthKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tp_title_details.url
	 * @mbg.generated
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.id
	 * @return  the value of tp_title_details.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.id
	 * @param id  the value for tp_title_details.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.title
	 * @return  the value of tp_title_details.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.title
	 * @param title  the value for tp_title_details.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.tax_no
	 * @return  the value of tp_title_details.tax_no
	 * @mbg.generated
	 */
	public String getTaxNo() {
		return taxNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.tax_no
	 * @param taxNo  the value for tp_title_details.tax_no
	 * @mbg.generated
	 */
	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo == null ? null : taxNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.addr
	 * @return  the value of tp_title_details.addr
	 * @mbg.generated
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.addr
	 * @param addr  the value for tp_title_details.addr
	 * @mbg.generated
	 */
	public void setAddr(String addr) {
		this.addr = addr == null ? null : addr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.phone
	 * @return  the value of tp_title_details.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.phone
	 * @param phone  the value for tp_title_details.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.bank_type
	 * @return  the value of tp_title_details.bank_type
	 * @mbg.generated
	 */
	public String getBankType() {
		return bankType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.bank_type
	 * @param bankType  the value for tp_title_details.bank_type
	 * @mbg.generated
	 */
	public void setBankType(String bankType) {
		this.bankType = bankType == null ? null : bankType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.bank_no
	 * @return  the value of tp_title_details.bank_no
	 * @mbg.generated
	 */
	public String getBankNo() {
		return bankNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.bank_no
	 * @param bankNo  the value for tp_title_details.bank_no
	 * @mbg.generated
	 */
	public void setBankNo(String bankNo) {
		this.bankNo = bankNo == null ? null : bankNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.title_type
	 * @return  the value of tp_title_details.title_type
	 * @mbg.generated
	 */
	public String getTitleType() {
		return titleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.title_type
	 * @param titleType  the value for tp_title_details.title_type
	 * @mbg.generated
	 */
	public void setTitleType(String titleType) {
		this.titleType = titleType == null ? null : titleType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.attach
	 * @return  the value of tp_title_details.attach
	 * @mbg.generated
	 */
	public String getAttach() {
		return attach;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.attach
	 * @param attach  the value for tp_title_details.attach
	 * @mbg.generated
	 */
	public void setAttach(String attach) {
		this.attach = attach == null ? null : attach.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.create_time
	 * @return  the value of tp_title_details.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.create_time
	 * @param createTime  the value for tp_title_details.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.from_user_name
	 * @return  the value of tp_title_details.from_user_name
	 * @mbg.generated
	 */
	public String getFromUserName() {
		return fromUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.from_user_name
	 * @param fromUserName  the value for tp_title_details.from_user_name
	 * @mbg.generated
	 */
	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName == null ? null : fromUserName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.to_user_name
	 * @return  the value of tp_title_details.to_user_name
	 * @mbg.generated
	 */
	public String getToUserName() {
		return toUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.to_user_name
	 * @param toUserName  the value for tp_title_details.to_user_name
	 * @mbg.generated
	 */
	public void setToUserName(String toUserName) {
		this.toUserName = toUserName == null ? null : toUserName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.msg_type
	 * @return  the value of tp_title_details.msg_type
	 * @mbg.generated
	 */
	public String getMsgType() {
		return msgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.msg_type
	 * @param msgType  the value for tp_title_details.msg_type
	 * @mbg.generated
	 */
	public void setMsgType(String msgType) {
		this.msgType = msgType == null ? null : msgType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.event
	 * @return  the value of tp_title_details.event
	 * @mbg.generated
	 */
	public String getEvent() {
		return event;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.event
	 * @param event  the value for tp_title_details.event
	 * @mbg.generated
	 */
	public void setEvent(String event) {
		this.event = event == null ? null : event.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.code_auth_key
	 * @return  the value of tp_title_details.code_auth_key
	 * @mbg.generated
	 */
	public String getCodeAuthKey() {
		return codeAuthKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.code_auth_key
	 * @param codeAuthKey  the value for tp_title_details.code_auth_key
	 * @mbg.generated
	 */
	public void setCodeAuthKey(String codeAuthKey) {
		this.codeAuthKey = codeAuthKey == null ? null : codeAuthKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tp_title_details.url
	 * @return  the value of tp_title_details.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tp_title_details.url
	 * @param url  the value for tp_title_details.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}
}