package com.mc.pojo;

public class ZhaohangBilling {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.trading_day
     *
     * @mbg.generated
     */
    private String tradingDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.transaction_time
     *
     * @mbg.generated
     */
    private String transactionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.interest_date
     *
     * @mbg.generated
     */
    private String interestDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.transaction_type
     *
     * @mbg.generated
     */
    private String transactionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.debit_amount
     *
     * @mbg.generated
     */
    private String debitAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.credit_amount
     *
     * @mbg.generated
     */
    private String creditAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.balance
     *
     * @mbg.generated
     */
    private String balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.serial_number
     *
     * @mbg.generated
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.instance_number
     *
     * @mbg.generated
     */
    private String instanceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.business_name
     *
     * @mbg.generated
     */
    private String businessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.purpose
     *
     * @mbg.generated
     */
    private String purpose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.business_number
     *
     * @mbg.generated
     */
    private String businessNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.business_summary
     *
     * @mbg.generated
     */
    private String businessSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.other_abstracts
     *
     * @mbg.generated
     */
    private String otherAbstracts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.branch_name
     *
     * @mbg.generated
     */
    private String branchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.accounts
     *
     * @mbg.generated
     */
    private String accounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.bank_number
     *
     * @mbg.generated
     */
    private String bankNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.bank_name
     *
     * @mbg.generated
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.bank_address
     *
     * @mbg.generated
     */
    private String bankAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.company_branch_name
     *
     * @mbg.generated
     */
    private String companyBranchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.company_account
     *
     * @mbg.generated
     */
    private String companyAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.information_signs
     *
     * @mbg.generated
     */
    private String informationSigns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.isany_attachment
     *
     * @mbg.generated
     */
    private String isanyAttachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.stamping_mark
     *
     * @mbg.generated
     */
    private String stampingMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.extended_abstract
     *
     * @mbg.generated
     */
    private String extendedAbstract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.analysis_code
     *
     * @mbg.generated
     */
    private String analysisCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.bill_number
     *
     * @mbg.generated
     */
    private String billNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhaohang_billing.internal_number
     *
     * @mbg.generated
     */
    private String internalNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.id
     *
     * @return the value of zhaohang_billing.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.id
     *
     * @param id the value for zhaohang_billing.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.trading_day
     *
     * @return the value of zhaohang_billing.trading_day
     *
     * @mbg.generated
     */
    public String getTradingDay() {
        return tradingDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.trading_day
     *
     * @param tradingDay the value for zhaohang_billing.trading_day
     *
     * @mbg.generated
     */
    public void setTradingDay(String tradingDay) {
        this.tradingDay = tradingDay == null ? null : tradingDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.transaction_time
     *
     * @return the value of zhaohang_billing.transaction_time
     *
     * @mbg.generated
     */
    public String getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.transaction_time
     *
     * @param transactionTime the value for zhaohang_billing.transaction_time
     *
     * @mbg.generated
     */
    public void setTransactionTime(String transactionTime) {
        this.transactionTime = transactionTime == null ? null : transactionTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.interest_date
     *
     * @return the value of zhaohang_billing.interest_date
     *
     * @mbg.generated
     */
    public String getInterestDate() {
        return interestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.interest_date
     *
     * @param interestDate the value for zhaohang_billing.interest_date
     *
     * @mbg.generated
     */
    public void setInterestDate(String interestDate) {
        this.interestDate = interestDate == null ? null : interestDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.transaction_type
     *
     * @return the value of zhaohang_billing.transaction_type
     *
     * @mbg.generated
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.transaction_type
     *
     * @param transactionType the value for zhaohang_billing.transaction_type
     *
     * @mbg.generated
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.debit_amount
     *
     * @return the value of zhaohang_billing.debit_amount
     *
     * @mbg.generated
     */
    public String getDebitAmount() {
        return debitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.debit_amount
     *
     * @param debitAmount the value for zhaohang_billing.debit_amount
     *
     * @mbg.generated
     */
    public void setDebitAmount(String debitAmount) {
        this.debitAmount = debitAmount == null ? null : debitAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.credit_amount
     *
     * @return the value of zhaohang_billing.credit_amount
     *
     * @mbg.generated
     */
    public String getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.credit_amount
     *
     * @param creditAmount the value for zhaohang_billing.credit_amount
     *
     * @mbg.generated
     */
    public void setCreditAmount(String creditAmount) {
        this.creditAmount = creditAmount == null ? null : creditAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.balance
     *
     * @return the value of zhaohang_billing.balance
     *
     * @mbg.generated
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.balance
     *
     * @param balance the value for zhaohang_billing.balance
     *
     * @mbg.generated
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.summary
     *
     * @return the value of zhaohang_billing.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.summary
     *
     * @param summary the value for zhaohang_billing.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.serial_number
     *
     * @return the value of zhaohang_billing.serial_number
     *
     * @mbg.generated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.serial_number
     *
     * @param serialNumber the value for zhaohang_billing.serial_number
     *
     * @mbg.generated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.instance_number
     *
     * @return the value of zhaohang_billing.instance_number
     *
     * @mbg.generated
     */
    public String getInstanceNumber() {
        return instanceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.instance_number
     *
     * @param instanceNumber the value for zhaohang_billing.instance_number
     *
     * @mbg.generated
     */
    public void setInstanceNumber(String instanceNumber) {
        this.instanceNumber = instanceNumber == null ? null : instanceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.business_name
     *
     * @return the value of zhaohang_billing.business_name
     *
     * @mbg.generated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.business_name
     *
     * @param businessName the value for zhaohang_billing.business_name
     *
     * @mbg.generated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.purpose
     *
     * @return the value of zhaohang_billing.purpose
     *
     * @mbg.generated
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.purpose
     *
     * @param purpose the value for zhaohang_billing.purpose
     *
     * @mbg.generated
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.business_number
     *
     * @return the value of zhaohang_billing.business_number
     *
     * @mbg.generated
     */
    public String getBusinessNumber() {
        return businessNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.business_number
     *
     * @param businessNumber the value for zhaohang_billing.business_number
     *
     * @mbg.generated
     */
    public void setBusinessNumber(String businessNumber) {
        this.businessNumber = businessNumber == null ? null : businessNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.business_summary
     *
     * @return the value of zhaohang_billing.business_summary
     *
     * @mbg.generated
     */
    public String getBusinessSummary() {
        return businessSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.business_summary
     *
     * @param businessSummary the value for zhaohang_billing.business_summary
     *
     * @mbg.generated
     */
    public void setBusinessSummary(String businessSummary) {
        this.businessSummary = businessSummary == null ? null : businessSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.other_abstracts
     *
     * @return the value of zhaohang_billing.other_abstracts
     *
     * @mbg.generated
     */
    public String getOtherAbstracts() {
        return otherAbstracts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.other_abstracts
     *
     * @param otherAbstracts the value for zhaohang_billing.other_abstracts
     *
     * @mbg.generated
     */
    public void setOtherAbstracts(String otherAbstracts) {
        this.otherAbstracts = otherAbstracts == null ? null : otherAbstracts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.branch_name
     *
     * @return the value of zhaohang_billing.branch_name
     *
     * @mbg.generated
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.branch_name
     *
     * @param branchName the value for zhaohang_billing.branch_name
     *
     * @mbg.generated
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.name
     *
     * @return the value of zhaohang_billing.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.name
     *
     * @param name the value for zhaohang_billing.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.accounts
     *
     * @return the value of zhaohang_billing.accounts
     *
     * @mbg.generated
     */
    public String getAccounts() {
        return accounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.accounts
     *
     * @param accounts the value for zhaohang_billing.accounts
     *
     * @mbg.generated
     */
    public void setAccounts(String accounts) {
        this.accounts = accounts == null ? null : accounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.bank_number
     *
     * @return the value of zhaohang_billing.bank_number
     *
     * @mbg.generated
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.bank_number
     *
     * @param bankNumber the value for zhaohang_billing.bank_number
     *
     * @mbg.generated
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber == null ? null : bankNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.bank_name
     *
     * @return the value of zhaohang_billing.bank_name
     *
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.bank_name
     *
     * @param bankName the value for zhaohang_billing.bank_name
     *
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.bank_address
     *
     * @return the value of zhaohang_billing.bank_address
     *
     * @mbg.generated
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.bank_address
     *
     * @param bankAddress the value for zhaohang_billing.bank_address
     *
     * @mbg.generated
     */
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress == null ? null : bankAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.company_branch_name
     *
     * @return the value of zhaohang_billing.company_branch_name
     *
     * @mbg.generated
     */
    public String getCompanyBranchName() {
        return companyBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.company_branch_name
     *
     * @param companyBranchName the value for zhaohang_billing.company_branch_name
     *
     * @mbg.generated
     */
    public void setCompanyBranchName(String companyBranchName) {
        this.companyBranchName = companyBranchName == null ? null : companyBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.company_account
     *
     * @return the value of zhaohang_billing.company_account
     *
     * @mbg.generated
     */
    public String getCompanyAccount() {
        return companyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.company_account
     *
     * @param companyAccount the value for zhaohang_billing.company_account
     *
     * @mbg.generated
     */
    public void setCompanyAccount(String companyAccount) {
        this.companyAccount = companyAccount == null ? null : companyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.company_name
     *
     * @return the value of zhaohang_billing.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.company_name
     *
     * @param companyName the value for zhaohang_billing.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.information_signs
     *
     * @return the value of zhaohang_billing.information_signs
     *
     * @mbg.generated
     */
    public String getInformationSigns() {
        return informationSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.information_signs
     *
     * @param informationSigns the value for zhaohang_billing.information_signs
     *
     * @mbg.generated
     */
    public void setInformationSigns(String informationSigns) {
        this.informationSigns = informationSigns == null ? null : informationSigns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.isany_attachment
     *
     * @return the value of zhaohang_billing.isany_attachment
     *
     * @mbg.generated
     */
    public String getIsanyAttachment() {
        return isanyAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.isany_attachment
     *
     * @param isanyAttachment the value for zhaohang_billing.isany_attachment
     *
     * @mbg.generated
     */
    public void setIsanyAttachment(String isanyAttachment) {
        this.isanyAttachment = isanyAttachment == null ? null : isanyAttachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.stamping_mark
     *
     * @return the value of zhaohang_billing.stamping_mark
     *
     * @mbg.generated
     */
    public String getStampingMark() {
        return stampingMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.stamping_mark
     *
     * @param stampingMark the value for zhaohang_billing.stamping_mark
     *
     * @mbg.generated
     */
    public void setStampingMark(String stampingMark) {
        this.stampingMark = stampingMark == null ? null : stampingMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.extended_abstract
     *
     * @return the value of zhaohang_billing.extended_abstract
     *
     * @mbg.generated
     */
    public String getExtendedAbstract() {
        return extendedAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.extended_abstract
     *
     * @param extendedAbstract the value for zhaohang_billing.extended_abstract
     *
     * @mbg.generated
     */
    public void setExtendedAbstract(String extendedAbstract) {
        this.extendedAbstract = extendedAbstract == null ? null : extendedAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.analysis_code
     *
     * @return the value of zhaohang_billing.analysis_code
     *
     * @mbg.generated
     */
    public String getAnalysisCode() {
        return analysisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.analysis_code
     *
     * @param analysisCode the value for zhaohang_billing.analysis_code
     *
     * @mbg.generated
     */
    public void setAnalysisCode(String analysisCode) {
        this.analysisCode = analysisCode == null ? null : analysisCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.bill_number
     *
     * @return the value of zhaohang_billing.bill_number
     *
     * @mbg.generated
     */
    public String getBillNumber() {
        return billNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.bill_number
     *
     * @param billNumber the value for zhaohang_billing.bill_number
     *
     * @mbg.generated
     */
    public void setBillNumber(String billNumber) {
        this.billNumber = billNumber == null ? null : billNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.order_number
     *
     * @return the value of zhaohang_billing.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.order_number
     *
     * @param orderNumber the value for zhaohang_billing.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaohang_billing.internal_number
     *
     * @return the value of zhaohang_billing.internal_number
     *
     * @mbg.generated
     */
    public String getInternalNumber() {
        return internalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaohang_billing.internal_number
     *
     * @param internalNumber the value for zhaohang_billing.internal_number
     *
     * @mbg.generated
     */
    public void setInternalNumber(String internalNumber) {
        this.internalNumber = internalNumber == null ? null : internalNumber.trim();
    }
}